churchdb_www/create/routes.py
from flask import Blueprint, render_template, url_for, request, abort
from flask_login import login_required, current_user

from churchdb_www.models import db, Person

import churchdb_www.utils.validate_input as validate_input

create = Blueprint('create', __name__)

@create.route('/', methods=['GET', 'POST'])
@login_required
def index():
    if not current_user.is_admin:
        abort(401)

    if request.method == 'POST':
        first_name = request.form.get('first_name', "", type=str)
        last_name = request.form.get('last_name', "", type=str)
        fiscal_code = request.form.get('fiscal_code', "", type=str)
        birth_date = request.form.get('birth_date', "", type=str)
        email_address = request.form.get('email_address', "", type=str)
        phone_number = request.form.get('phone_number', "", type=str)

        if not validate_input.validate_all(first_name, last_name, fiscal_code, birth_date, email_address, phone_number):
            abort(400)

        person = Person(first_name=first_name, last_name=last_name, fiscal_code=fiscal_code, date_of_birth=birth_date, email_address=email_address, phone_number=phone_number)
        db.session.add(person)
        db.session.commit()

    return render_template('create.html')

churchdb_www/main/routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, abort
from flask_login import login_user
from werkzeug.security import check_password_hash
from churchdb_www.models import User

main = Blueprint('main', __name__)

def check_credentials(username: str, password: str) -> bool:
    """Check if the given credentials are correct.

    Args:
        username (str): username
        password (str): password

    Returns:
        bool: True if the credentials are correct, False otherwise
    """
    
    user = User.query.filter_by(username=username).first()
    if user:
        return check_password_hash(user.password, password)

    return False


@main.route('/', methods=["GET", "POST"])
def index():
    if request.method == "POST":
        username = request.form.get('username')
        password = request.form.get('password')
        
        if check_credentials(username, password):
            user = User.query.filter_by(username=username).first()
            login_user(user)

            return redirect(url_for('search.index'))
        else:
            flash('Invalid username or password')

    return render_template('main.html', no_navbar=True)

@main.route('/test_abort')
def test():
    abort(400)
    return "This will never be executed"

churchdb_www/search/routes.py
from flask import Blueprint, render_template, request, abort
from flask_login import login_required
from flask_sqlalchemy import *

from churchdb_www.models import Person, BaptismalCertificate, FirstCommunionCertificate, ConfirmationCertificate, MarriageCertificate, DeathCertificate

import churchdb_www.utils.validate_input as validate_input

search = Blueprint('search', __name__)


@search.route('/')
@login_required
def index():
    return render_template('search.html')


def filter_persons(first_name=None, last_name=None, fiscal_code=None, birth_date=None, email=None, phone=None):
    persons = Person.query

    if first_name:
        persons = persons.filter_by(first_name=first_name)
    if last_name:
        persons = persons.filter_by(last_name=last_name)
    if fiscal_code:
        persons = persons.filter_by(fiscal_code=fiscal_code)
    if birth_date:
        persons = persons.filter_by(date_of_birth=birth_date)
    if email:
        persons = persons.filter_by(email=email)
    if phone:
        persons = persons.filter_by(phone=phone)

    return persons


def get_baptismal_certificates(ids: list):
    return BaptismalCertificate.query.filter(
        BaptismalCertificate.released_to_id.in_(ids)).all()


def get_first_communion_certificates(ids: list):
    return FirstCommunionCertificate.query.filter(
        FirstCommunionCertificate.released_to_id.in_(ids)).all()


def get_confirmation_certificates(ids: list):
    return ConfirmationCertificate.query.filter(
        ConfirmationCertificate.released_to_id.in_(ids)).all()


def get_marriage_certificates(ids: list):
    return MarriageCertificate.query.filter(MarriageCertificate.released_to_id_1.in_(
        ids) | MarriageCertificate.released_to_id_2.in_(ids)).all()


def get_death_certificates(ids: list):
    return DeathCertificate.query.filter(
        DeathCertificate.released_to_id.in_(ids)).all()


@search.route('/get_results', methods=['POST'])
@login_required
def get_results():
    first_name = request.form.get('first_name', "", type=str)
    last_name = request.form.get('last_name', "", type=str)
    fiscal_code = request.form.get('fiscal_code', "", type=str)
    birth_date = request.form.get('birth_date', "", type=str)
    email_address = request.form.get('email_address', "", type=str)
    phone_number = request.form.get('phone_number', "", type=str)
    search_option = request.form.get('search_option', "", type=str)

    if not validate_input.validate_all(first_name, last_name, fiscal_code, birth_date, email_address, phone_number, search_option):
        abort(400)

    if search_option == 'certificates':
        ids = [person.id for person in filter_persons(
            first_name, last_name, fiscal_code, birth_date, email_address, phone_number)]

        results = []
        results += get_baptismal_certificates(ids)
        results += get_first_communion_certificates(ids)
        results += get_confirmation_certificates(ids)
        results += get_marriage_certificates(ids)
        results += get_death_certificates(ids)
    else:
        results = [person for person in filter_persons(
            first_name, last_name, fiscal_code, birth_date, email_address, phone_number)]

    return {"results": results}

churchdb_www/templates/base.html
<!DOCTYPE html>
<html lang="it">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ChurchDB</title>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
</head>

<body>
    {% if not no_navbar is defined %}
        {% include 'navbar.html' %}
    {% endif %}
    
    {% block body %}{% endblock %}
</body>

</html>

churchdb_www/templates/create.html
{% extends 'user_explorer.html' %}

{% block title %}Person Creator{% endblock %}

{% block button_text %}Create{% endblock %}

{% block extra_container %}
    <script defer>
        let navbar_page = document.querySelector("#navbarSupportedContent > ul > li:nth-child(2) > a")
        navbar_page.classList.add("active")
    </script>
{% endblock %}

churchdb_www/templates/error.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>ChurchDB</title>

    <style id="" media="all">
        /* cyrillic-ext */
        @font-face {
            font-family: 'Montserrat';
            font-style: normal;
            font-weight: 700;
            font-display: swap;
            src: url(/fonts.gstatic.com/s/montserrat/v25/JTUSjIg1_i6t8kCHKm459WRhyzbi.woff2) format('woff2');
            unicode-range: U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F;
        }

        /* cyrillic */
        @font-face {
            font-family: 'Montserrat';
            font-style: normal;
            font-weight: 700;
            font-display: swap;
            src: url(/fonts.gstatic.com/s/montserrat/v25/JTUSjIg1_i6t8kCHKm459W1hyzbi.woff2) format('woff2');
            unicode-range: U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116;
        }

        /* vietnamese */
        @font-face {
            font-family: 'Montserrat';
            font-style: normal;
            font-weight: 700;
            font-display: swap;
            src: url(/fonts.gstatic.com/s/montserrat/v25/JTUSjIg1_i6t8kCHKm459WZhyzbi.woff2) format('woff2');
            unicode-range: U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB;
        }

        /* latin-ext */
        @font-face {
            font-family: 'Montserrat';
            font-style: normal;
            font-weight: 700;
            font-display: swap;
            src: url(/fonts.gstatic.com/s/montserrat/v25/JTUSjIg1_i6t8kCHKm459Wdhyzbi.woff2) format('woff2');
            unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
        }

        /* latin */
        @font-face {
            font-family: 'Montserrat';
            font-style: normal;
            font-weight: 700;
            font-display: swap;
            src: url(/fonts.gstatic.com/s/montserrat/v25/JTUSjIg1_i6t8kCHKm459Wlhyw.woff2) format('woff2');
            unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
        }

        /* cyrillic-ext */
        @font-face {
            font-family: 'Montserrat';
            font-style: normal;
            font-weight: 900;
            font-display: swap;
            src: url(/fonts.gstatic.com/s/montserrat/v25/JTUSjIg1_i6t8kCHKm459WRhyzbi.woff2) format('woff2');
            unicode-range: U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F;
        }

        /* cyrillic */
        @font-face {
            font-family: 'Montserrat';
            font-style: normal;
            font-weight: 900;
            font-display: swap;
            src: url(/fonts.gstatic.com/s/montserrat/v25/JTUSjIg1_i6t8kCHKm459W1hyzbi.woff2) format('woff2');
            unicode-range: U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116;
        }

        /* vietnamese */
        @font-face {
            font-family: 'Montserrat';
            font-style: normal;
            font-weight: 900;
            font-display: swap;
            src: url(/fonts.gstatic.com/s/montserrat/v25/JTUSjIg1_i6t8kCHKm459WZhyzbi.woff2) format('woff2');
            unicode-range: U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB;
        }

        /* latin-ext */
        @font-face {
            font-family: 'Montserrat';
            font-style: normal;
            font-weight: 900;
            font-display: swap;
            src: url(/fonts.gstatic.com/s/montserrat/v25/JTUSjIg1_i6t8kCHKm459Wdhyzbi.woff2) format('woff2');
            unicode-range: U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF;
        }

        /* latin */
        @font-face {
            font-family: 'Montserrat';
            font-style: normal;
            font-weight: 900;
            font-display: swap;
            src: url(/fonts.gstatic.com/s/montserrat/v25/JTUSjIg1_i6t8kCHKm459Wlhyw.woff2) format('woff2');
            unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
        }
    </style>

    <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename = 'css/error_page.css') }}" />

</head>

<body>
    <div id="notfound">
        <div class="notfound">
            <div class="notfound-404">
                <h1>{{ error_code }}</h1>
                <h2>{{ error_msg }}</h2>
            </div>
            <a href="{{ url_for('main.index') }}">Homepage</a>
        </div>
    </div>

</body>

</html>

churchdb_www/templates/main.html
{% extends 'base.html' %}

{% block body %}
<style>
  .login {
    min-height: 100vh;
  }

  .bg-image {
    background-image: url('https://scontent-mxp2-1.xx.fbcdn.net/v/t1.6435-9/92779701_125418655748788_7085832054188802048_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=973b4a&_nc_ohc=YenyPseK3v4AX_mq4dX&_nc_ht=scontent-mxp2-1.xx&oh=00_AT8Y0FAm8SONHxSBy4dRos45q89OaZysnDKMKi4Ld3XASQ&oe=62F790FC');
    background-size: cover;
    background-position: center;
  }

  .login-heading {
    font-weight: 300;
  }

  .btn-login {
    font-size: 0.9rem;
    letter-spacing: 0.05rem;
    padding: 0.75rem 1rem;
  }
</style>

<div class="container-fluid ps-md-0">
  <div class="row g-0">
    <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
    <div class="col-md-8 col-lg-6">
      <div class="login d-flex align-items-center py-5">
        <div class="container">
          <div class="row">
            <div class="col-md-9 col-lg-8 mx-auto">
              <h3 class="login-heading mb-4 text-center">Welcome back!</h3>

              {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="d-grid">
                  <div class=" rounded text-center text-white fw-bold p-2 mb-3 bg-danger">
                    {{ messages[0] }}.
                  </div>
                </div>
                {% endif %}
              {% endwith %}

              <!-- Sign In Form -->
              <form method="POST" action="{{ url_for('main.index') }}">
                <div class="form-floating mb-3">
                  <input name="username" type="text" class="form-control" id="floatingInput"
                    placeholder="Enter your username here">
                  <label for="floatingInput">Username</label>
                </div>

                <div class="form-floating mb-3">
                  <input name="password" type="password" class="form-control" id="floatingPassword" placeholder="Password">
                  <label for="floatingPassword">Password</label>
                </div>

                <div class="d-grid">
                  <button class="btn btn-lg btn-primary btn-login text-uppercase fw-bold mb-2" type="submit">Sign
                    in</button>
                </div>

              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

churchdb_www/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">ChurchDB</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('search.index') }}">Search</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('create.index') }}">Create</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown">
                        Dropdown
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled">Disabled</a>
                </li>
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

churchdb_www/templates/search.html
{% extends 'user_explorer.html' %}

{% block title %}Explore Database{% endblock %}

{% block button_text %}Search{% endblock %}

{% block extra_form %}
<div class="row">
    <div class="col mb-3">
        <select name="search_option" class="form-select" aria-label="Default select example">
            <option value="persons">Persons</option>
            <option value="certificates" selected>Certificates</option>
        </select>
    </div>  
</div>
{% endblock %}

{% block extra_container %}
    <style>
        .overflowable {
            overflow-y: auto;
            height: 50vh;
            -ms-overflow-style: none;
            scrollbar-width: none;
        }

        .overflowable::-webkit-scrollbar {
            display: none;
        }

        .header {
            position: sticky;
            top: 0;
        }
    </style>

    <div class="container overflowable">
        <div class="card-body">
            <table class="table">
                <thead id="results_thead" class="header">
                    <tr>
                        <th scope="col" class="text-center bg-white header">Type</th>
                        <th scope="col" class="text-center bg-white header">First Name</th>
                        <th scope="col" class="text-center bg-white header">Last Name</th>
                        <th scope="col" class="text-center bg-white header">Fiscal Code</th>
                        <th scope="col" class="text-center bg-white header" colspan="2">Links</th>
                    </tr>  
                </thead>
                <tbody id="results_tbody" class="overflow-scroll">
                    
                </tbody>
            </table>
        </div>
    </div>

    <script defer>
        let navbar_page = document.querySelector("#navbarSupportedContent > ul > li:nth-child(1) > a")
        navbar_page.classList.add("active")
    </script>

    <script src="{{ url_for('static', filename = 'js/search.js') }}"></script>
{% endblock %}  

churchdb_www/templates/user_explorer.html
{% extends 'base.html' %}

{% block body %}

<div class="container my-3">
    <div class="card">
        <div class="card-header text-center fw-bold text-uppercase" style="background-color: #e6e6e6">
            {% block title %}{% endblock %}
        </div>
        <div class="card-body">
            <form method="POST" id="form">
                <div class="row mb-3">
                    <div class="col">
                        <div class="input-group">
                            <div class="input-group-text">
                                <i class="bi-credit-card"></i>
                            </div>
                            <input id="fiscal_code_input" name="fiscal_code" type="text" class="form-control" placeholder="Fiscal Code">
                        </div>
                    </div>
                </div>

                <div class="row mb-3">
                    <div class="col-md-8">
                        <div class="input-group">
                            <div class="input-group-text">
                                <i class="bi-person-lines-fill"></i>
                            </div>
                            <input name="first_name" id="first_name_input" type="text" class="form-control" placeholder="First Name">
                            <input name="last_name" id="last_name_input" type="text" class="form-control" placeholder="Last Name">
                        </div>
                        
                    </div>

                    <div class="col-md-4">
                        <div class="input-group">
                            <div class="input-group-text">
                                <i class="fa fa-birthday-cake"></i>
                            </div>
                            <input name="birth_date" id="birth_date_input" type="date" class="form-control">
                        </div>
                    </div>
                </div>

                <div class="row mb-3">
                    <div class="col-md-6">
                        <div class="input-group">
                            <div class="input-group-text">
                                <i class="bi-envelope"></i>
                            </div>
                            <input name="email_address" id="email_address_input" type="email" class="form-control" placeholder="Email">
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="input-group">
                            <div class="input-group-text">
                                <i class="bi-telephone"></i>
                            </div>
                            <input name="phone_number" id="phone_number_input" type="text" class="form-control" placeholder="Phone Number">
                        </div>
                    </div>
                </div>

                {% block extra_form %}{% endblock %}

                <div class="row">
                    <div class="col d-grid">
                        <button type="submit" class="btn btn-primary fw-bold text-uppercase">
                            {% block button_text %}{% endblock %}
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="{{ url_for('static', filename = 'js/form_verifier.js') }}"></script>

{% block extra_container %}{% endblock %}

{% endblock %}